export const INPUT_TYPE={
    FIRST:"FIRST NAME",
    LAST:"LAST NAME",
    EMAIL:"EMAIL ADDRESS",
    DOB:"DATE OF BIRTH",
    PHONE:"PHONE NUMBER",
    PASSWORD:"SET PASSWORD",
    CONFIRM:"CONFIRM PASSWORD"

  }